#for debug deployment
# add -f docker-compose-production to build with production environment
volumes:
  blog-postgres-volume:

services:
  web-api:
    build: .
    env_file:
      - config/env/debug/webapi.env
    ports:
      #      - host-port:container-port
      - 8100:8000
    command: 'blog.main:app --host 0.0.0.0 --port 8000 --reload'
    depends_on:
      - database
  database:
    build:
      dockerfile: Dockerfile_db
    ports:
#      - host-port:container-port
      - 5432:5432
    volumes:
      - 'blog-postgres-volume:/var/lib/postgresql/data'