version: "3.8"
#for production deployment
volumes:
  blog-postgres-volume:

services:
  web-api:
    build: .
    ports:
#      - host-port:container-port
      - 8100:8100
    env_file:
      - env/production/webapi.env
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
#      - host-port:container-port
      - 5432:5432
    volumes:
      - blog-postgres-volume:/var/lib/postgresql/data
    env_file:
      - env/production/database.env