# configured for debug deployment by default
# for production deployment call docker-compose -f docker-compose.yml -f config/docker-compose-prod.yml
volumes:
  blog-postgres-volume:

services:
  web-api:
    build:
      context: .
      dockerfile: config/Dockerfile
    env_file:
      - config/env/debug/webapi.env
    ports:
      #      - host-port:container-port
      - 8100:8000
    command: 'uvicorn blog.main:app --host 0.0.0.0 --port 8000 --reload'
    depends_on:
      - database
  database:
    build:
      context: .
      dockerfile: config/Dockerfile_db
    ports:
#      - host-port:container-port
      - 5432:5432
    volumes:
      - 'blog-postgres-volume:/var/lib/postgresql/data'