#for production deployment
volumes:
  blog-postgres-volume:

services:
  web-api:
    volumes:
# run using local code, not the one copied to container
      - ./blog:/code/blog
    command: 'uvicorn blog.main:app --host 0.0.0.0 --port 8000 --reload'
    env_file:
      - config/env/debug/webapi.env