#for production deployment
volumes:
  blog-postgres-volume:

services:
  web-api:
    command: 'uvicorn blog.main:app --host 0.0.0.0 --port 8000'
    env_file:
      - config/env/production/webapi.env